name: Push Branch

on:
  push:
    branches:
      - '*'

env: {}

jobs:
  package:
    name: Package
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create NuGet Package (static)
        run: nuget pack glew-2.3.1/nuget/glew.static.nuspec -BasePath glew-2.3.1 -NonInteractive
      - name: Create NuGet Package (DLL)
        run: nuget pack glew-2.3.1/nuget/glew.dynamic.nuspec -BasePath glew-2.3.1 -NonInteractive
      - name: Upload NuGet Packages
        uses: actions/upload-artifact@v7
        with:
          name: NuGet
          path: '**/*.nupkg'
